#!/usr/bin/bash

git clone https://github.com/hevok/denigma # Cloning (maybe better checkout).

cd denigma

virtualenv env
. env/bin/activate
pip install -r denigma/requirements/project.txt

denigma/manage.py syncdb --all
denigma/manage.py migrate --fake
denigma/manage.py runserver
