#!/usr/bin/bash

git clone https://github.com/hevok/denigma # Cloning (maybe better checkout).

cd denigma

virtualenv env
. env/bin/activate
pip install -r denigma/requirements/project.txt

./manage.py syncdb --all
./manage.py migrate --fake
./manage.py runserver
