# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'AgingSignature'
        db.create_table('expressions_agingsignature', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('mapping', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('entrez_gene_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('gene_name', self.gf('django.db.models.fields.CharField')(max_length=93, blank=True)),
            ('gene_symbol', self.gf('django.db.models.fields.CharField')(max_length=20, blank=True)),
            ('human_brain', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('human_kidney', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('human_muscle_1', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('human_muscle_2', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_brain', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_cochlea', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_eye', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_heart', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_hematopoietic', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_hippocampus', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_kidney', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_liver', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_lung', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_muscle', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_myoblast', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('mouse_neocortex', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_cardiac', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_extraocular', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_glia', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_hippocampal_ca1_1', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_hippocampal_ca1_2', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_hippocampus', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_larynge', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_muscle', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_oculomotor', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_spinal', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('rat_stromal', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('n_genes', self.gf('django.db.models.fields.IntegerField')()),
            ('n_overexpressed', self.gf('django.db.models.fields.IntegerField')()),
            ('n_underexpressed', self.gf('django.db.models.fields.IntegerField')()),
            ('p_value', self.gf('django.db.models.fields.FloatField')()),
            ('q_value', self.gf('django.db.models.fields.FloatField')()),
            ('taxid', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('classification', self.gf('django.db.models.fields.CharField')(max_length=8)),
        ))
        db.send_create_signal('expressions', ['AgingSignature'])

        # Adding model 'AgingSignatureChi'
        db.create_table('expressions_agingsignaturechi', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('mapping', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('entrez_gene_id', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('gene_name', self.gf('django.db.models.fields.CharField')(max_length=89, blank=True)),
            ('gene_symbol', self.gf('django.db.models.fields.CharField')(max_length=20, blank=True)),
            ('human_brain', self.gf('django.db.models.fields.FloatField')()),
            ('human_kidney', self.gf('django.db.models.fields.FloatField')()),
            ('human_muscle_1', self.gf('django.db.models.fields.FloatField')()),
            ('human_muscle_2', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_brain', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_cochlea', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_eye', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_heart', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_hematopoietic', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_hippocampus', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_kidney', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_liver', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_lung', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_muscle', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_myoblast', self.gf('django.db.models.fields.FloatField')()),
            ('mouse_neocortex', self.gf('django.db.models.fields.FloatField')()),
            ('rat_cardiac', self.gf('django.db.models.fields.FloatField')()),
            ('rat_extraocular', self.gf('django.db.models.fields.FloatField')()),
            ('rat_glia', self.gf('django.db.models.fields.FloatField')()),
            ('rat_hippocampal_ca1_1', self.gf('django.db.models.fields.FloatField')()),
            ('rat_hippocampal_ca1_2', self.gf('django.db.models.fields.FloatField')()),
            ('rat_hippocampus', self.gf('django.db.models.fields.FloatField')()),
            ('rat_larynge', self.gf('django.db.models.fields.FloatField')()),
            ('rat_muscle', self.gf('django.db.models.fields.FloatField')()),
            ('rat_oculomotor', self.gf('django.db.models.fields.FloatField')()),
            ('rat_spinal', self.gf('django.db.models.fields.FloatField')()),
            ('rat_stromal', self.gf('django.db.models.fields.FloatField')()),
            ('n_genes', self.gf('django.db.models.fields.IntegerField')()),
            ('p_value', self.gf('django.db.models.fields.FloatField')()),
            ('taxid', self.gf('django.db.models.fields.IntegerField')()),
            ('classification', self.gf('django.db.models.fields.CharField')(max_length=5)),
        ))
        db.send_create_signal('expressions', ['AgingSignatureChi'])


    def backwards(self, orm):
        
        # Deleting model 'AgingSignature'
        db.delete_table('expressions_agingsignature')

        # Deleting model 'AgingSignatureChi'
        db.delete_table('expressions_agingsignaturechi')


    models = {
        'expressions.agemap': {
            'Meta': {'object_name': 'AgeMap'},
            'adrenals_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'cerebellum_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'classification': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'empirical_meta_analysis_p_value': ('django.db.models.fields.FloatField', [], {}),
            'empirical_meta_analysis_value': ('django.db.models.fields.FloatField', [], {}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'eye_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'gene_ontology': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'gonads_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'heart_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lung_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'spinal_cord_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'spleen_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'thymus_age_coef': ('django.db.models.fields.FloatField', [], {}),
            'unigene': ('django.db.models.fields.CharField', [], {'max_length': '9'})
        },
        'expressions.agingsignature': {
            'Meta': {'object_name': 'AgingSignature'},
            'classification': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gene_name': ('django.db.models.fields.CharField', [], {'max_length': '93', 'blank': 'True'}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'human_brain': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'human_kidney': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'human_muscle_1': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'human_muscle_2': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mouse_brain': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_cochlea': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_eye': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_heart': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_hematopoietic': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_hippocampus': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_kidney': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_liver': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_lung': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_muscle': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_myoblast': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'mouse_neocortex': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'n_genes': ('django.db.models.fields.IntegerField', [], {}),
            'n_overexpressed': ('django.db.models.fields.IntegerField', [], {}),
            'n_underexpressed': ('django.db.models.fields.IntegerField', [], {}),
            'p_value': ('django.db.models.fields.FloatField', [], {}),
            'q_value': ('django.db.models.fields.FloatField', [], {}),
            'rat_cardiac': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_extraocular': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_glia': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_hippocampal_ca1_1': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_hippocampal_ca1_2': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_hippocampus': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_larynge': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_muscle': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_oculomotor': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_spinal': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'rat_stromal': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'taxid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'expressions.agingsignaturechi': {
            'Meta': {'object_name': 'AgingSignatureChi'},
            'classification': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gene_name': ('django.db.models.fields.CharField', [], {'max_length': '89', 'blank': 'True'}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'human_brain': ('django.db.models.fields.FloatField', [], {}),
            'human_kidney': ('django.db.models.fields.FloatField', [], {}),
            'human_muscle_1': ('django.db.models.fields.FloatField', [], {}),
            'human_muscle_2': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mouse_brain': ('django.db.models.fields.FloatField', [], {}),
            'mouse_cochlea': ('django.db.models.fields.FloatField', [], {}),
            'mouse_eye': ('django.db.models.fields.FloatField', [], {}),
            'mouse_heart': ('django.db.models.fields.FloatField', [], {}),
            'mouse_hematopoietic': ('django.db.models.fields.FloatField', [], {}),
            'mouse_hippocampus': ('django.db.models.fields.FloatField', [], {}),
            'mouse_kidney': ('django.db.models.fields.FloatField', [], {}),
            'mouse_liver': ('django.db.models.fields.FloatField', [], {}),
            'mouse_lung': ('django.db.models.fields.FloatField', [], {}),
            'mouse_muscle': ('django.db.models.fields.FloatField', [], {}),
            'mouse_myoblast': ('django.db.models.fields.FloatField', [], {}),
            'mouse_neocortex': ('django.db.models.fields.FloatField', [], {}),
            'n_genes': ('django.db.models.fields.IntegerField', [], {}),
            'p_value': ('django.db.models.fields.FloatField', [], {}),
            'rat_cardiac': ('django.db.models.fields.FloatField', [], {}),
            'rat_extraocular': ('django.db.models.fields.FloatField', [], {}),
            'rat_glia': ('django.db.models.fields.FloatField', [], {}),
            'rat_hippocampal_ca1_1': ('django.db.models.fields.FloatField', [], {}),
            'rat_hippocampal_ca1_2': ('django.db.models.fields.FloatField', [], {}),
            'rat_hippocampus': ('django.db.models.fields.FloatField', [], {}),
            'rat_larynge': ('django.db.models.fields.FloatField', [], {}),
            'rat_muscle': ('django.db.models.fields.FloatField', [], {}),
            'rat_oculomotor': ('django.db.models.fields.FloatField', [], {}),
            'rat_spinal': ('django.db.models.fields.FloatField', [], {}),
            'rat_stromal': ('django.db.models.fields.FloatField', [], {}),
            'taxid': ('django.db.models.fields.IntegerField', [], {})
        },
        'expressions.lin2002': {
            'Meta': {'object_name': 'Lin2002'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '223', 'blank': 'True'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'hap4oe1': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hap4oe2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hxk2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'low_glucose1': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'low_glucose2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '9'})
        },
        'expressions.rapamycin': {
            'Meta': {'object_name': 'Rapamycin'},
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fpr1_8_rapamycin_mean': ('django.db.models.fields.FloatField', [], {}),
            'fpr1_8_rapamycin_replicate_1': ('django.db.models.fields.FloatField', [], {'blank': 'True'}),
            'fpr1_8_rapamycin_replicate_2': ('django.db.models.fields.FloatField', [], {}),
            'fpr1_8_rapamycin_replicate_3': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ly_83583_mean': ('django.db.models.fields.FloatField', [], {'blank': 'True'}),
            'ly_83583_replicate_1': ('django.db.models.fields.FloatField', [], {}),
            'ly_83583_replicate_2': ('django.db.models.fields.FloatField', [], {}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'rapamycin_mean': ('django.db.models.fields.FloatField', [], {'blank': 'True'}),
            'rapamycin_replicate_1': ('django.db.models.fields.FloatField', [], {}),
            'rapamycin_replicate_2': ('django.db.models.fields.FloatField', [], {})
        },
        'expressions.rapamycin_protein': {
            'Meta': {'object_name': 'rapamycin_protein'},
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'protein': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'protein_function': ('django.db.models.fields.CharField', [], {'max_length': '82'})
        },
        'expressions.sip2delta_aging': {
            'Meta': {'object_name': 'sip2delta_aging'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '172'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '5', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_process': ('django.db.models.fields.CharField', [], {'max_length': '56'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'specific_process': ('django.db.models.fields.CharField', [], {'max_length': '29', 'blank': 'True'})
        },
        'expressions.sip2delta_wt': {
            'Meta': {'object_name': 'sip2delta_wt'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '178'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_process': ('django.db.models.fields.CharField', [], {'max_length': '56'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'specific_process': ('django.db.models.fields.CharField', [], {'max_length': '38', 'blank': 'True'})
        },
        'expressions.snf4delta_aging': {
            'Meta': {'object_name': 'snf4delta_aging'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '155'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '7', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_process': ('django.db.models.fields.CharField', [], {'max_length': '56'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'specific_process': ('django.db.models.fields.CharField', [], {'max_length': '29', 'blank': 'True'})
        },
        'expressions.snf4delta_wt': {
            'Meta': {'object_name': 'snf4delta_wt'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '127'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_process': ('django.db.models.fields.CharField', [], {'max_length': '56'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'specific_process': ('django.db.models.fields.CharField', [], {'max_length': '32', 'blank': 'True'})
        },
        'expressions.wt_aging': {
            'Meta': {'object_name': 'wt_aging'},
            'description': ('django.db.models.fields.CharField', [], {'max_length': '146'}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fold_change': ('django.db.models.fields.FloatField', [], {}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main_process': ('django.db.models.fields.CharField', [], {'max_length': '56'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'specific_process': ('django.db.models.fields.CharField', [], {'max_length': '54', 'blank': 'True'})
        },
        'expressions.wtcrvsyepd1': {
            'Meta': {'object_name': 'wtcrvsyepd1'},
            'al': ('django.db.models.fields.FloatField', [], {}),
            'dr': ('django.db.models.fields.FloatField', [], {}),
            'dr_al': ('django.db.models.fields.FloatField', [], {}),
            'entrez_gene_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gene_symbol': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'orf': ('django.db.models.fields.CharField', [], {'max_length': '12'})
        }
    }

    complete_apps = ['expressions']
